In [57]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import
np.set_printoptions(precision=3, suppress=True)

3부문 총, 국산, 수입거래표 및 고용표 불러오기

In [58]:
url_Tt_33 = "https://raw.githubusercontent.com/profguclass/IO-2025/main/Total_matrix_33sectors.csv"  # 총거래표(3부문) 불러오기
Tt_33 = pd.read_csv(url_Tt_33, thousands=',')

url_Dt_33 = "https://raw.githubusercontent.com/profguclass/IO-2025/main/Domestic_matrix_33sectors.csv"  # 국산거래표(3부문) 불러오기
Dt_33 = pd.read_csv(url_Dt_33, thousands=',')

url_It_33 = "https://raw.githubusercontent.com/profguclass/IO-2025/main/Imported_matrix_33sectors.csv"  # 수입거래표(3부문) 불러오기
It_33 = pd.read_csv(url_It_33, thousands=',')


In [59]:
Tt = Tt_33.to_numpy()  # numpy로 불러오기
Dt = Dt_33.to_numpy()
It = It_33.to_numpy()

Tt

array([['농림수산품', 4256311, 3473, ..., 0.0, 0.0, 91017764.0],
       ['광산품', 2055, 2999, ..., 0.0, 0.0, 223457977.0],
       ['음식료품', 13490896, 16188, ..., 0.0, 0.0, 229316612.0],
       ...,
       ['생산세(보조금공제)', -27016, -6795, ..., nan, nan, nan],
       ['부가가치계', 34901541, 2157106, ..., nan, nan, nan],
       ['총투입계', 74068069, 5326597, ..., nan, nan, nan]], dtype=object)

In [60]:
Tt_1 = Tt[0:40,1:50].astype(float)
Dm_1 = Dt[0:33,1:50].astype(float)
Im_1 = It[0:33,1:50].astype(float)

In [61]:
Ct = Tt_1[-1,0:33]  # 총산출액 벡터
Va = Tt_1[-2,0:33]  # 부가가치 벡터

In [63]:
Ct_m = np.tile(Ct, reps=[33,1]) # 총산출액 벡터를 3번 행반복

In [64]:
At = (Tt_1[0:33,0:33]/Ct_m)   # 총투입계수
Ad = (Dm_1[0:33,0:33]/Ct_m)   # 국산투입계수
Ai = (Im_1[0:33,0:33]/Ct_m)   # 수입투입계수
Av = (Va/Ct).reshape([1,33])  # 부가가치율 벡터

print('총투입계수표 \n', At.round(3),'\n')
print('국산투입계수표 \n', Ad.round(3),'\n')
print('수입투입계수표 \n', Ai.round(3),'\n')
print('부가가치율 \n', Av.round(3))



총투입계수표 
 [[0.057 0.001 0.246 ... 0.001 0.001 0.001]
 [0.    0.001 0.    ... 0.    0.    0.   ]
 [0.182 0.003 0.204 ... 0.043 0.013 0.011]
 ...
 [0.001 0.007 0.001 ... 0.042 0.005 0.   ]
 [0.001 0.006 0.002 ... 0.008 0.008 0.   ]
 [0.004 0.003 0.    ... 0.002 0.001 0.022]] 

국산투입계수표 
 [[0.051 0.001 0.189 ... 0.001 0.001 0.001]
 [0.    0.001 0.    ... 0.    0.    0.   ]
 [0.179 0.003 0.127 ... 0.04  0.013 0.011]
 ...
 [0.001 0.007 0.001 ... 0.036 0.004 0.   ]
 [0.001 0.006 0.002 ... 0.008 0.007 0.   ]
 [0.004 0.003 0.    ... 0.002 0.001 0.022]] 

수입투입계수표 
 [[0.007 0.    0.056 ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.003 0.    0.077 ... 0.002 0.    0.   ]
 ...
 [0.    0.    0.    ... 0.005 0.    0.   ]
 [0.    0.    0.    ... 0.    0.001 0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]] 

부가가치율 
 [[0.471 0.405 0.235 0.183 0.291 0.187 0.242 0.264 0.195 0.325 0.307 0.218
  0.252 0.199 0.271 0.472 0.205 0.449 0.418 0.536 0.434 0.327 0.523 0.625
  0.702 0.519 0.6

In [73]:
df_At = pd.DataFrame(At)  #pandas로 내보내기
df_Ad = pd.DataFrame(Ad)  #pandas로 내보내기
df_Ai = pd.DataFrame(Ai)  #pandas로 내보내기
df_Av = pd.DataFrame(Av)                  #pandas로 내보내기

##### 생산유발계수(Lf)

In [74]:
Lf = np.linalg.inv(np.identity(33)-Ad)  # 생산유발계수

Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수의 행합
Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수의 열합

Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,33])  #영향력 계수
Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,33])  #감응도 계수

print('생산유발계수 \n', Lf.round(3),'\n')

print('생산유발계수의 행합 \n', Lf_rw_sm.round(3),'\n')
print('생산유발계수의 열합 \n', Lf_cl_sm.round(3),'\n')

print('부문별 영향력계수 \n', Lf_bwd.round(3),'\n')
print('부문별 감응도계수 \n', Lf_fwd.round(3),'\n')

생산유발계수 
 [[1.102 0.007 0.242 ... 0.018 0.014 0.011]
 [0.001 1.001 0.001 ... 0.001 0.001 0.001]
 [0.233 0.019 1.204 ... 0.066 0.041 0.031]
 ...
 [0.002 0.009 0.003 ... 1.04  0.006 0.002]
 [0.005 0.011 0.006 ... 0.011 1.011 0.004]
 [0.005 0.004 0.002 ... 0.003 0.002 1.023]] 

생산유발계수의 행합 
 [1.964 2.061 2.207 1.928 2.147 1.286 1.889 2.209 1.818 2.152 1.718 2.032
 2.189 2.414 2.177 1.967 1.527 1.974 2.058 1.756 1.644 2.208 1.678 1.564
 1.517 1.797 1.657 1.418 1.569 1.642 1.753 2.007 2.485] 

생산유발계수의 열합 
 [1.672 1.125 2.276 1.502 1.813 1.921 3.413 1.4   2.388 2.063 1.913 2.039
 1.485 1.942 1.192 2.238 2.603 1.404 1.195 3.177 2.812 1.92  2.015 2.249
 1.659 3.141 2.292 1.943 1.039 1.084 1.167 1.242 1.09 ] 

부문별 영향력계수 
 [[1.038 1.09  1.167 1.019 1.135 0.68  0.999 1.168 0.961 1.138 0.908 1.075
  1.157 1.276 1.151 1.04  0.807 1.044 1.088 0.928 0.869 1.167 0.887 0.827
  0.802 0.95  0.876 0.75  0.83  0.868 0.927 1.061 1.314]] 

부문별 감응도계수 
 [[0.884 0.595 1.203 0.794 0.959 1.016 1.805 0.74  1.263 1.0

In [75]:
df_Lf = pd.DataFrame(Lf.round(3))  #pandas로 내보내기

#### 수입유발계수(Li)

In [76]:
Li = (Ai@Lf).round(3)  #수입유발계수
print('수입유발계수 \n', Li)

수입유발계수 
 [[0.021 0.001 0.07  ... 0.004 0.003 0.002]
 [0.05  0.076 0.04  ... 0.025 0.036 0.029]
 [0.023 0.004 0.095 ... 0.01  0.007 0.004]
 ...
 [0.    0.    0.    ... 0.005 0.    0.   ]
 [0.    0.    0.    ... 0.    0.001 0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]]


In [77]:
df_Li = pd.DataFrame(Li.round(3))  #pandas로 내보내기

#### 부가가치유발계수(Lv)

In [78]:
Va_m = np.diagflat(Av)  # 부가가치율의 대각행렬
Va_m

array([[0.471, 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.   , 0.405, 0.   , ..., 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.235, ..., 0.   , 0.   , 0.   ],
       ...,
       [0.   , 0.   , 0.   , ..., 0.559, 0.   , 0.   ],
       [0.   , 0.   , 0.   , ..., 0.   , 0.45 , 0.   ],
       [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ]])

In [79]:
Lv = (Va_m@Lf).round(3)  #부가가치유발계수
print('부가가치유발계수 \n', Lv)

부가가치유발계수 
 [[0.519 0.003 0.114 ... 0.008 0.007 0.005]
 [0.    0.405 0.    ... 0.    0.    0.   ]
 [0.055 0.004 0.283 ... 0.016 0.01  0.007]
 ...
 [0.001 0.005 0.002 ... 0.581 0.004 0.001]
 [0.002 0.005 0.003 ... 0.005 0.455 0.002]
 [0.    0.    0.    ... 0.    0.    0.   ]]


In [80]:
df_Lv = pd.DataFrame(Lv.round(3))  # pandas로 내보내기

In [81]:
# CSV파일로 결과 내보내기
df_At.to_csv('총투입계수.csv', encoding='utf_8-sig')
df_Ad.to_csv('국산투입계수.csv', encoding='utf_8-sig')
df_Ai.to_csv('수입투입계수.csv', encoding='utf_8-sig')

df_Lf.to_csv('생산유발계수.csv', encoding='utf_8-sig')
df_Lv.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
df_Li.to_csv('수입유발계수.csv', encoding='utf_8-sig')